
project_id = "lygbrcsdjjwzdmyxbmbu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_manual_linking = false

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions.ai-chat]
verify_jwt = true

[edge-runtime]
enabled = true
port = 54323
ip_version = "ipv4"

[functions]
enabled = true
