// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lygbrcsdjjwzdmyxbmbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5Z2JyY3Nkamp3emRteXhibWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDU5MDQsImV4cCI6MjA2NDQ4MTkwNH0.Kio3p7zQRvA0vg8DUEtWNl0jgpyHikh5fu7pMnXarls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);